language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "apollo-rsps"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - git fetch --unshallow
  - ./gradlew -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="$SONAR_TOKEN" sonarqube
  - openssl aes-256-cbc
    -K $encrypted_18db87a19112_key
    -iv $encrypted_18db87a19112_iv
    -in gradle/config/github_deploy_key.enc -out gradle/config/github_deploy_key -d
  - chmod 600 gradle/config/github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add gradle/config/github_deploy_key
  - test $TRAVIS_BRANCH = "kotlin-experiments-docs" && gradle publishGhPages

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
